version: '3'
services:
  mysql:
    build:
      context: ./database
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u user -ppassword" ]
      interval: 10s
      timeout: 5s
      retries: 3

  spring-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy