name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ubo_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      DATABASE_HOSTNAME: "localhost"
      DATABASE_PORT: 3306
      DATABASE_NAME: "ubo_db"
      DATABASE_USER: "user"
      DATABASE_PASSWORD: "password"
      DATABASE_ROOT_PASSWORD: "root"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Download MySQL Connector
        run: |
          wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.26/mysql-connector-java-8.0.26.jar
          mkdir -p libs
          mv mysql-connector-java-8.0.26.jar libs/

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test

      - name: Set up Docker
        uses: docker/login-action@v1
        with:
          username: "haitbourhim"
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: success()
        run: |
          docker build -t haitbourhim/csa-backend:latest .
          docker push haitbourhim/csa-backend:latest

      - name: Build and push MySQL Docker image
        run: |
          docker build -t haitbourhim/csa-database:latest ./database
          docker push haitbourhim/csa-database:latest