name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/setup-gradle@v2
        with:
          gradle-version: '8.5'

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test

      - name: Set up Docker
        uses: docker/login-action@v1
        with:
          username: "haitbourhim"
          password: "zissizriddikilos"

      - name: Build and push Docker image
        if: success()
        run: |
          docker build -t haitbourhim/csa-backend:latest .
          docker push haitbourhim/csa-backend:latest

      - name: Build and push MySQL Docker image
        run: |
          docker build -t haitbourhim/csa-database:latest ./database
          docker push haitbourhim/csa-database:latest



